### ISSUE TITLE
Fix innodb_buffer_pools

### ISSUE THREAD

**Issue by john-f-chamberlain** [lexiconn-internet-services/public-templates#4]
See lexiconn-internet-services/server-configurator#22

**Comment by john-f-chamberlain** [comment]
MySQL 8:

/etc/my.cnf

change line:
innodb_buffer_pool_instances=32

to:
innodb_buffer_pool_instances=2

to match buffer_pool_size of 2 GB
?

Check MySQL 5.7 too

**Comment by robfico** [comment]
Yes.  :)
